spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/harmony?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

mybatis-plus:
  # 配置mapper.xml的位置
  mapper-locations: classpath*:/mapper/**/*.xml
  # 配置实体类的扫描路径
  type-aliases-package: com.example.schedule.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.baomidou: debug
